### PR TITLE
Fix parameter order in CSSStyleDeclaration

### PR DESCRIPTION
**Pull request by theqp**
This is a breaking change.

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by thomashoneyman** [comment]
@garyb I see the 👍 -- is this something we want to standardize on? The foreign-import object going last?

**Comment by garyb** [comment]
Not so much the foreign-import object going last as "the thing being operated on", as that's the convention generally everywhere - collections, refs, is (should) be the case with the other web libraries, etc. 🙂

**Review by thomashoneyman — APPROVED** [review]

**Comment by JordanMartinez** [comment]
Is this another breaking change to make in `v0.15.0`?

**Comment by thomashoneyman** [comment]
Let's do it!

**Review by JordanMartinez — APPROVED** [review]

**Pull request merged**
